'#
  Authors
Torsten Pook, torsten.pook@uni-goettingen.de

Copyright (C) 2017 -- 2018  Torsten Pook

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
'#

#' Compute costs of a breeding program
#'
#' Function to derive the costs of a breeding program / population-list
#' @param population population-list
#' @param phenotyping.costs Costs for the generation of a phenotype
#' @param genotyping.costs Costs for the geneation of a genotype
#' @param fix.costs one time occuring fixed costs
#' @param fix.costs.annual annually occuring fixed costs
#' @param profit.per.bv profit generated by bv per animal
#' @param database Groups to consider
#' @param gen Generations to consider
#' @param interest.rate Applied yearly interest rate
#' @param base.gen Base generation (application of interest rate)
#' @export

compute.costs <- function(population, phenotyping.costs = 10, genotyping.costs = 100, fix.costs= 0, fix.costs.annual = 0,
                          profit.per.bv = 1, database=NULL, gen=NULL,
                          interest.rate = 1, base.gen=1){


  if(length(gen)>0){
    database <- cbind(rep(gen,each=2), rep(1:2, length(gen)))
  }
  if(length(database)==0){
    generation <- nrow(population$info$size)
    database <- cbind(rep(1:generation, each=2), 1:2)
  }

  gen <- unique(database[,1])
  size <- population$info$size[gen,]
  generation = length(gen)

  t <- length(phenotyping.costs)
  if(t != (2*generation)){
    if(t == 1){
      phenotyping.costs <- matrix(phenotyping.costs, nrow=generation, ncol=2)
    }
    if(t==generation){
      phenotyping.costs <- matrix(phenotyping.costs, nrow=generation, ncol=2, byrow=FALSE)
    }
    if(t==2){
      phenotyping.costs <- matrix(phenotyping.costs, nrow=generation, ncol=2, byrow=TRUE)
      if(generation==2){
        print("Specify if phenotyping.costs are per generation or per sex. Default use: Gender")
      }
    }
  }

  t <- length(genotyping.costs)
  if(t != (2*generation)){
    if(t == 1){
      genotyping.costs <- matrix(genotyping.costs, nrow=generation, ncol=2)
    }
    if(t==generation){
      genotyping.costs <- matrix(genotyping.costs, nrow=generation, ncol=2, byrow=FALSE)
    }
    if(t==2){
      genotyping.costs <- matrix(genotyping.costs, nrow=generation, ncol=2, byrow=TRUE)
      if(generation==2){
        print("Specify if genotyping.costs are per generation or per sex. Default use: Gender")
      }
    }
  }

  t <- length(profit.per.bv)
  if(t != (2*generation)){
    if(t == 1){
      profit.per.bv <- matrix(profit.per.bv, nrow=generation, ncol=2)
    }
    if(t==generation){
      profit.per.bv <- matrix(profit.per.bv, nrow=generation, ncol=2, byrow=FALSE)
    }
    if(t==2){
      profit.per.bv <- matrix(profit.per.bv, nrow=generation, ncol=2, byrow=TRUE)
      if(generation==2){
        print("Specify if profit.per.bv are per generation or per sex. Default use: Gender")
      }
    }
  }

  if(length(fix.costs.annual)!=length(gen)){
    fix.costs.annual <- rep(fix.costs.annual, length.out=length(gen))
  }

  if(interest.rate!=1){
    phenotyping.costs <- phenotyping.costs * (interest.rate ^ (gen-base.gen))
    genotyping.costs <- genotyping.costs * (interest.rate ^ (gen-base.gen))
    profit.per.bv <- profit.per.bv * (interest.rate ^ (gen-base.gen))
    fix.costs.annual <- fix.costs.annual * (interest.rate ^ (gen-base.gen))
  }

  costs_pheno <- matrix(0, nrow=generation, ncol=2)
  costs_geno <- matrix(0, nrow=generation, ncol=2)
  profit_bv <- matrix(0, nrow=generation, ncol=2)

  for(index in 1:nrow(database)){
    activ <- database[index,]
    row <- which(activ[1]==gen)
    for(index2 in 1:length(population$breeding[[activ[1]]][[activ[2]]])){
      costs_pheno[row,activ[2]] <- costs_pheno[row,activ[2]] + population$breeding[[activ[1]]][[activ[2]]][[index]][[15]] * phenotyping.costs[row, activ[2]]
      costs_geno[row,activ[2]] <- costs_geno[row,activ[2]] + population$breeding[[activ[1]]][[activ[2]]][[index]][[16]] * genotyping.costs[row, activ[2]]
      profit_bv[row,activ[2]] <- profit_bv[row,activ[2]] + population$breeding[[activ[1]]][[activ[2]+6]][1,index] * profit.per.bv[row, activ[2]]
    }
  }

  costs_pergroup <- costs_pheno + costs_geno

  annual_gain <- rowSums(profit_bv) - rowSums(costs_pheno) - rowSums(costs_geno) - fix.costs.annual
  graphics::plot(gen, annual_gain)

  return(annual_gain)
}

